apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
      - name: nginx
        image: yourdockerhub/nginx-site:latest  # Updated by GitHub Actions
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-site
  namespace: web
spec:
  selector:
    app: nginx-site
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourorg/gitops-manifests.git
    targetRevision: HEAD
    path: manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
